language: rust
cache: cargo
rust:
    - stable
    - nightly
script:
    - cargo build --verbose --features "pancurses-backend termion-backend"
    - cargo test --verbose --features "pancurses-backend termion-backend"
