[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
build = "build.rs"
categories = ["command-line-interface", "gui"]
description = "A TUI (Text User Interface) library focused on ease-of-use."
documentation = "https://gyscos.github.io/Cursive/cursive/index.html"
exclude = ["doc", "assets"]
keywords = ["ncurses", "TUI", "UI"]
license = "MIT"
name = "cursive"
readme = "Readme.md"
repository = "https://github.com/gyscos/Cursive"
version = "0.4.0"

[badges]

[badges.travis-ci]
repository = "gyscos/Cursive"

[build-dependencies]

[build-dependencies.skeptic]
optional = true
version = "0.6"

[dependencies]
chan = "0.1.18"
num = "0.1"
odds = "0.2"
owning_ref = "0.2.4"
toml = "0.2"
unicode-segmentation = "1.0"
unicode-width = "0.1"

[dependencies.bear-lib-terminal]
optional = true
version = "1.3.1"

[dependencies.chan-signal]
optional = true
version = "0.1"

[dependencies.ncurses]
features = ["wide"]
optional = true
version = "5.85.0"

[dependencies.pancurses]
features = ["wide"]
optional = true
version = "0.7"

[dependencies.termion]
optional = true
version = "1.1.1"

[dev-dependencies]
rand = "0.3"
skeptic = "0.6"

[features]
default = ["ncurses"]
pancurses-backend = ["pancurses"]
termion-backend = ["termion", "chan-signal"]

[lib]
name = "cursive"
