[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
description = "A TUI library based on ncurses-rs"
documentation = "https://gyscos.github.io/Cursive/cursive/index.html"
keywords = ["ncurses", "TUI"]
license = "MIT"
name = "cursive"
readme = "Readme.md"
repository = "https://github.com/Gyscos/cursive"
version = "0.0.2"

[dependencies]
ncurses = "5.80.0"
toml = "0.1"
unicode-segmentation = "0.1.2"

[lib]
name = "cursive"
