[package]
name = "cursive"
version = "0.1.0"
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
description = "A TUI library based on ncurses-rs"
license = "MIT"
repository = "https://github.com/Gyscos/cursive"
readme = "Readme.md"
keywords = ["ncurses", "TUI"]

[lib]
name = "cursive"

[dependencies]
toml = "0.1"

[dependencies.ncurses]
git = "https://github.com/jeaye/ncurses-rs"

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"

[[example]]
name = "lorem"
path = "examples/lorem.rs"

[[example]]
name = "dialog"
path = "examples/dialog.rs"

[[example]]
name = "logs"
path = "examples/logs.rs"

[[example]]
name = "mutation"
path = "examples/mutation.rs"

[[example]]
name = "edit"
path = "examples/edit.rs"

[[example]]
name = "key_codes"
path = "examples/key_codes.rs"
