[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
description = "A TUI library based on ncurses-rs."
documentation = "https://gyscos.github.io/Cursive/cursive/index.html"
exclude = ["doc", "assets"]
keywords = ["ncurses", "TUI"]
license = "MIT"
name = "cursive"
readme = "Readme.md"
repository = "https://github.com/gyscos/Cursive"
version = "0.1.1"

[dependencies]
ncurses = "5.80.0"
odds = "0.2.14"
toml = "0.1"
unicode-segmentation = "0.1.2"
unicode-width = "0.1.3"

[dev-dependencies]
rand = "0.3"

[lib]
name = "cursive"
