[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
categories = ["command-line-interface", "gui"]
description = "A TUI (Text User Interface) library focused on ease-of-use."
documentation = "https://gyscos.github.io/Cursive/cursive/index.html"
exclude = ["doc/**", "assets/**", "examples/**"]
keywords = ["ncurses", "TUI", "UI"]
license = "MIT"
name = "cursive"
readme = "Readme.md"
repository = "https://github.com/gyscos/Cursive"
version = "0.7.5-alpha.0"

[badges.travis-ci]
repository = "gyscos/Cursive"


[dependencies]
log = "0.3"
num = "0.1"
odds = "0.2"
owning_ref = "0.3"
toml = "0.4"
unicode-segmentation = "1.0"
unicode-width = "0.1"

[dependencies.chan]
optional = true
version = "0.1.18"

[dependencies.chan-signal]
optional = true
version = "0.3"

[dependencies.bear-lib-terminal]
optional = true
version = "1.3.1"

[dependencies.ncurses]
features = ["wide"]
optional = true
version = "5.86.0"

[dependencies.pancurses]
features = ["wide"]
optional = true
version = "0.12"

[dependencies.termion]
optional = true
version = "1.5.0"

[dev-dependencies]
rand = "0.3"

[features]
default = ["ncurses-backend"]

ncurses-backend = ["ncurses"]
termion-backend = ["termion", "chan", "chan-signal"]
pancurses-backend = ["pancurses"]
blt-backend = ["bear-lib-terminal"]

[lib]
name = "cursive"
