[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
categories = [
    "command-line-interface",
    "gui",
]
description = "A TUI (Text User Interface) library focused on ease-of-use."
documentation = "https://docs.rs/cursive"
exclude = [
    "doc/**",
    "assets/**",
    "examples/**",
]
keywords = [
    "ncurses",
    "TUI",
    "UI",
]
license = "MIT"
name = "cursive"
readme = "Readme.md"
repository = "https://github.com/gyscos/Cursive"
version = "0.7.6-alpha.0"

[badges.travis-ci]
repository = "gyscos/Cursive"

[dependencies]
log = "0.4"
maplit = "1.0.0"
num = "0.1"
owning_ref = "0.3"
toml = "0.4"
unicode-segmentation = "1.0"
unicode-width = "0.1"

[dependencies.bear-lib-terminal]
optional = true
version = "1.3.1"

[dependencies.chan]
optional = true
version = "0.1.18"

[dependencies.chan-signal]
optional = true
version = "0.3"

[dependencies.ncurses]
features = ["wide"]
optional = true
version = "5.87.0"

[dependencies.pancurses]
features = ["wide"]
optional = true
version = "0.13"

[dependencies.termion]
optional = true
version = "1.5.0"

[dev-dependencies]
rand = "0.4"

[features]
blt-backend = ["bear-lib-terminal"]
default = ["ncurses-backend"]
ncurses-backend = ["ncurses"]
pancurses-backend = ["pancurses"]
termion-backend = [
    "termion",
    "chan",
    "chan-signal",
]

[lib]
name = "cursive"
