[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
description = "A TUI (Text User Interface) library focused on ease-of-use."
documentation = "https://gyscos.github.io/Cursive/cursive/index.html"
exclude = ["doc", "assets"]
keywords = ["ncurses", "TUI", "UI"]
license = "MIT"
name = "cursive"
readme = "Readme.md"
repository = "https://github.com/gyscos/Cursive"
version = "0.2.5"

[dependencies]
ncurses = "5.80.0"
odds = "0.2"
toml = "0.2"
unicode-segmentation = "0.1"
unicode-width = "0.1"

[dev-dependencies]
rand = "0.3"

[lib]
name = "cursive"
