[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
build = "build.rs"
description = "A TUI (Text User Interface) library focused on ease-of-use."
documentation = "https://gyscos.github.io/Cursive/cursive/index.html"
exclude = ["doc", "assets"]
keywords = ["ncurses", "TUI", "UI"]
license = "MIT"
name = "cursive"
readme = "Readme.md"
repository = "https://github.com/gyscos/Cursive"
version = "0.3.1"

[build-dependencies]
skeptic = "0.6"

[dependencies]
odds = "0.2"
toml = "0.2"
unicode-segmentation = "0.1"
unicode-width = "0.1"

[dependencies.ncurses]
version = "5.83.0"
features = ["wide"]
optional = true

[dependencies.pancurses]
version = "0.6"
features = ["wide"]
optional = true

[dependencies.termion]
version = "1.1.1"
optional = true

[dependencies.bear-lib-terminal]
version = "1.3.1"
optional = true

[dev-dependencies]
rand = "0.3"
skeptic = "0.6"

[features]
default = ["ncurses"]

[lib]
name = "cursive"
