name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: cd cursive && cargo check --all-features
    - name: Build
      run: cd cursive && cargo build --features "markdown pancurses-backend termion-backend crossterm-backend" --no-default-features --verbose
    - name: Run tests
      run: cd cursive && cargo test --features "markdown pancurses-backend termion-backend crossterm-backend" --no-default-features --verbose
