name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cd cursive && cargo build --features crossterm-backend --no-default-features --verbose
    - name: Run tests
      run: cd cursive && cargo test --features crossterm-backend --no-default-features --verbose
